name: Bug Report
description: Envoyer un rapport de bug
title: "[Bug]: "
labels: ["bug", "triage", "potentially-bug"]
assignees:
  - alexdieudonne
body:
  - type: markdown
    attributes:
      value: |
        Merci d'avoir pris votre temps pour remplir cet formulaire!
  - type: input
    id: contact
    attributes:
      label: Votre email
      description: Comment pouvons-nous vous contacter pour plus d'informations concernant votre bug?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    id: what-happened
    attributes:
      label: Qu'est ce qui s'est passé?
      description: Racontez nous ce qui s'est passé, qu'est ce que vous faisiez lorsque cela s'est produit, Vous pouvez rajouter aussi des images pour illustrer vos dires?
      placeholder: Dites nous tous !
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Qu'elle était votre version de Node JS?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (lastest)
    validations:
      required: true